### ISSUE TITLE
Create a separate branch for the 2.10 compatible version

### ISSUE THREAD

**Issue by dpursehouse** [ReviewAssistant/reviewassistant#15]
The master branch is now using the 2.11-SNAPSHOT API, so anyone that builds the plugin off master won't be able to deploy it on Gerrit version 2.10.

Please create a 2.10 branch off a point before the 2.11-SNAPSHOT update, to allow users to build it for 2.10.

Suggested branch name is `stable-2.10`, to follow convention of all the other Gerrit plugins.

Suggested branch point is d758e6579b8fc928c3dd7fd3352aa9247cfef737 which was the last commit before the 2.11-SNAPSHOT update was merged.

**Comment by nllptr** [comment]
Thanks a lot for the feedback. Really helpful for us students :+1:
