### ISSUE TITLE
Access to static field from instance method

### ISSUE THREAD

**Issue by dpursehouse** [ReviewAssistant/reviewassistant#23]
The following code in ReviewAssistant.java:

```
//TODO Move into addReviewers?
realUser = true;
addReviewers(change, finalMap);
realUser = false;
```

causes a warning from FindBugs:

> Write to static field com.github.reviewassistant.reviewassistant.ReviewAssistant.realUser from instance method com.github.reviewassistant.reviewassistant.ReviewAssistant.run()
> 
> This instance method writes to a static field. This is tricky to get correct if multiple instances are being manipulated, and generally bad practice.

The only other place it's used is in ChangeEventListener:

```
@Override public CurrentUser getCurrentUser() {
  if (!ReviewAssistant.realUser) {
    return pluginUser;
  } else {
    return identifiedUserFactory.create(change.getOwner());
  }
}
```

I don't think this is going to work as expected when there are multiple instances of the ReviewAssistant object, but at the moment I don't have a better solution.

**Comment by dpursehouse** [comment]
@GLundh or @sselberg any ideas?

**Comment by sselberg** [comment]
The context relies on state from ReviewAssistant.
So I would get the context from the ReviewAssistant instance, so instead of 

```
RequestContext old = tl.setContext(new RequestContext() {
```

I would go for:

```
RequestContext old = task.getContext();
```

You would have to move IdentifiedUser.GenericFactory to ReviewAssistent.java and get yourself a SchemaFactory or pass it:

```
RequestContext old = task.getContext(SchemaFactory<ReviewDb> db);
```

That seems more legit to me.

/Sven

**Comment by williamphan** [comment]
This was an issue we stumbled upon during early development and did not find any good solutions. We appreciate the help! #11 

Cheers!
