### ISSUE TITLE
Migrate this plugin to gerrit-review.googlesource.com?

### ISSUE THREAD

**Issue by dpursehouse** [ReviewAssistant/reviewassistant#26]
Would you be open to migrating this plugin into gerrit-review.googlesource.com and restructuring the branches to follow the same convention as the other plugins?  (i.e. have a master branch that always targets the latest snapshot API, and stable-2.x branches for the released APIs).

**Comment by nllptr** [comment]
I'm all for migrating.

**Comment by dpursehouse** [comment]
OK, that's good :)

I'll wait for responses from the others before going ahead with it though.

Note that once it's migrated, you'll need to create accounts on gerrit-review.googlesource.com by logging in with a Google account.  Then I can add you to the owner group so you have all the permissions to do code reviews and submit changes.

Also to be able to upload changes you'll need to submit the CLA document.  To do that, follow this link after creating your account:

https://gerrit-review.googlesource.com/#/settings/agreements

**Comment by williamphan** [comment]
Sure thing, I think Gustav also is positive with it.

**Comment by gustavjp** [comment]
Sounds good!

**Comment by gustavjp** [comment]
Is it the Android or Google CLA?

**Comment by dpursehouse** [comment]
Gerrit is licensed under "The Android Open Source Project".

**Comment by dpursehouse** [comment]
If we're OK to go ahead with this, I'll do it later this week.  Do you want to merge any PRs before then, or have them re-submitted through Gerrit after migration?

**Comment by nllptr** [comment]
I've registered over at google source. Tried to do some testing, but I simply don't have the time to do it properly. If @williamphan  and @gustavjp are ok with it, I suggest you migrate it as-is, and re-submit PRs after.

**Comment by williamphan** [comment]
Whichever you prefer is fine with me. :)

**Comment by dpursehouse** [comment]
OK, the project is now [available on gerrit-review](https://gerrit-review.googlesource.com/#/admin/projects/plugins/reviewassistant).

@nllptr and @gustavjp I added you to the owners group, so you should be able to apply `Code-Review+2` on the changes and I think also make config changes on the project itself to some extent.

@williamphan I couldn't find an account for you.  Ping me when/if you add one, and then I'll put you in the group too.

I've moved my PRs to code reviews over there.   I also created a new `stable-2.11` branch and moved main development to `master` instead of `develop`.

**Comment by williamphan** [comment]
@dpursehouse I've created one now, cheers!

**Comment by dpursehouse** [comment]
@williamphan and now you're also in the group.

I'll close this issue now.
